
name: Swift Lint

on:
  workflow_dispatch:

  push:

  pull_request:
    paths:
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  call-reusable-workflow-to-swift-lint:
    uses: Kjuly/swift-ci/.github/workflows/swift-lint.yml@main
    with:
      use_default_config: true
      force_exclude: true

